Update to latest lombok (1.18.16)
This change updates the pom.xml file to use version 1.18.16 of lombok.

Otherwise, without this change, when build with current java versions,
the following fatal build error occurs:

> [ERROR] Failed to execute goal
> org.apache.maven.plugins:maven-compiler-plugin:3.3:compile
> (default-compile) on project jcurl: Fatal error compiling:
> java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags